shortener/index/urls.py
from shortener.index.views import index, signup, signin, signout
from django.urls import path

app_name = "auth"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", signup, name="signup"),
    path("signin/", signin, name="signin"),
    path("signout/", signout, name="signout"),
]

shortener/urls/urls.py
# import path 경로 => localhost:8000/urls/

from django.urls import path
from shortener.urls.views import url_list, url_create, url_change


from rest_framework import routers
from shortener.urls.apis import *

router = routers.DefaultRouter()
router.register(r'urls', UserViewSet)
# localhost:8000/api/urls/~~~

app_name = "urls"
urlpatterns = [
    path("", url_list, name="url_list"),
    path("create/", url_create, name="url_create"),
    path("<str:action>/<int:url_id>/", url_change, name="url_change"),
]

shrinkers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path

from shortener.urls.views import url_redirect
from shortener.urls.urls import router as url_router


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Shrinkers API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    re_path(r"^swagger(?P<format>\.json|\.yaml)$", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    re_path(r"^swagger/$", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    re_path(r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),

    path("admin/", admin.site.urls),
    path("", include("shortener.index.urls")),
    path("urls/", include("shortener.urls.urls")),
    path("api/", include(url_router.urls)),

    path("<str:prefix>/<str:url>", url_redirect),
]

templates/includes/nav.html
{% load static %}
<!-- Sidenav -->
<nav
  class="
    sidenav
    navbar navbar-vertical
    fixed-left
    navbar-expand-xs navbar-light
    bg-white
  "
  id="sidenav-main"
>
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header d-flex align-items-center">
      <a class="navbar-brand" href="#">
        <img
          src="{% static 'assets/img/shrinkers_logo-cutout.png' %}"
          height="20"
          class="navbar-brand-img"
          alt="..."
        />
      </a>
      <div class="ml-auto">
        <!-- Sidenav toggler -->
        <div
          class="sidenav-toggler d-none d-xl-block"
          data-action="sidenav-unpin"
          data-target="#sidenav-main"
        >
          <div class="sidenav-toggler-inner">
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
            <i class="sidenav-toggler-line"></i>
          </div>
        </div>
      </div>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a
              class="nav-link active"
              href="#navbar-dashboards"
              data-toggle="collapse"
              role="button"
              aria-expanded="true"
              aria-controls="navbar-dashboards"
            >
              <i class="ni ni-shop text-primary"></i>
              <span class="nav-link-text">대시보드</span>
            </a>
            <div class="collapse show" id="navbar-dashboards">
              <ul class="nav nav-sm flex-column">
                <li class="nav-item">
                  <a href="{% url 'urls:url_list' %}" class="nav-link">
                    <span class="sidenav-mini-icon"> U </span>
                    <span class="sidenav-normal"> URL 리스트 </span>
                  </a>
                </li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/includes/top_nav.html
{% load static %}
<nav
  class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom"
>
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center ml-md-auto">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div
            class="pr-3 sidenav-toggler sidenav-toggler-dark"
            data-action="sidenav-pin"
            data-target="#sidenav-main"
          >
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link"
            href="#"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <i class="ni ni-bell-55"></i>
          </a>
          <div
            class="
              dropdown-menu dropdown-menu-xl dropdown-menu-right
              py-0
              overflow-hidden
            "
          >
            <!-- Dropdown header -->
            <div class="px-3 py-3">
              <h6 class="text-sm text-muted m-0">
                You have
                <strong class="text-primary">13</strong> notifications.
              </h6>
            </div>
            <!-- List group -->
            <div class="list-group list-group-flush">
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img
                      alt="Image placeholder"
                      src="{% static 'assets/img/theme/team-1.jpg' %}"
                      class="avatar rounded-circle"
                    />
                  </div>
                  <div class="col ml--2">
                    <div
                      class="d-flex justify-content-between align-items-center"
                    >
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">
                      Let's meet at Starbucks at 11:30. Wdyt?
                    </p>
                  </div>
                </div>
              </a>
            </div>
            <!-- View all -->
            <a
              href="#!"
              class="
                dropdown-item
                text-center text-primary
                font-weight-bold
                py-3
              "
              >View all</a
            >
          </div>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link"
            href="#"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <i class="ni ni-ungroup"></i>
          </a>
          <div
            class="
              dropdown-menu dropdown-menu-lg dropdown-menu-dark
              bg-default
              dropdown-menu-right
            "
          >
            <div class="row shortcuts px-4">
              <a href="#!" class="col-4 shortcut-item">
                <span
                  class="shortcut-media avatar rounded-circle bg-gradient-red"
                >
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
                <small>URLs</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span
                  class="shortcut-media avatar rounded-circle bg-gradient-info"
                >
                  <i class="ni ni-credit-card"></i>
                </span>
                <small>Payments</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span
                  class="shortcut-media avatar rounded-circle bg-gradient-green"
                >
                  <i class="ni ni-books"></i>
                </span>
                <small>Reports</small>
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center ml-auto ml-md-0">
        <li class="nav-item dropdown">
          <a
            class="nav-link pr-0"
            href="#"
            role="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img
                  alt="Image placeholder"
                  src="{% static 'assets/img/theme/team-4.jpg' %}"
                />
              </span>
              <div class="media-body ml-2 d-none d-lg-block">
                <span class="mb-0 text-sm font-weight-bold">Ryan Lee</span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="#!" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>프로필</span>
            </a>
            <a href="#!" class="dropdown-item">
              <i class="ni ni-settings-gear-65"></i>
              <span>설정</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'auth:signout' %}" class="dropdown-item">
              <i class="ni ni-user-run"></i>
              <span>로그아웃</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>