shortener/index/urls.py
from shortener.index.views import index, signup, signin, signout
from django.urls import path

app_name = "auth"

urlpatterns = [
    path("", index, name="index"),
    path("signup/", signup, name="signup"),
    path("signin/", signin, name="signin"),
    path("signout/", signout, name="signout"),
]

shortener/urls/urls.py
# import path 경로 => localhost:8000/urls/

from django.urls import path
from shortener.urls.views import url_list, url_create, url_change


from rest_framework import routers
from shortener.urls.apis import *

router = routers.DefaultRouter()
router.register(r'urls', UserViewSet)
# localhost:8000/api/urls/~~~

app_name = "urls"
urlpatterns = [
    path("", url_list, name="url_list"),
    path("create/", url_create, name="url_create"),
    path("<str:action>/<int:url_id>/", url_change, name="url_change"),
]

shrinkers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path

from shortener.urls.views import url_redirect
from shortener.urls.urls import router as url_router


from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Shrinkers API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    re_path(r"^swagger(?P<format>\.json|\.yaml)$", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    re_path(r"^swagger/$", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    re_path(r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),

    path("admin/", admin.site.urls),
    path("", include("shortener.index.urls")),
    path("urls/", include("shortener.urls.urls")),
    path("api/", include(url_router.urls)),

    path("<str:prefix>/<str:url>", url_redirect),
]

templates/base.html
{% load static %}

<!--
=========================================================
* Impact Design System - v1.0.0
=========================================================
* Product Page: https://www.creative-tim.com/product/impact-design-system
* Copyright 2010 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/impact-design-system/blob/master/LICENSE.md)
* Coded by Creative Tim
=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
      name="description"
      content="Start your development with a Dashboard for Bootstrap 4."
    />
    <meta name="author" content="Creative Tim" />
    <title>{% block title %}{% endblock %} | Shrinkers</title>

    <!-- Fonts -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700"
    />
    <!-- Icons -->
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}"
      type="text/css"
    />
    <!-- Page plugins -->
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/fullcalendar/dist/fullcalendar.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/sweetalert2/dist/sweetalert2.min.css' %}"
    />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Argon CSS -->
    <link
      rel="stylesheet"
      href="{% static 'css/dashboard.css' %}"
      type="text/css"
    />
    <!-- Core -->
    <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
    <!-- Optional JS -->
    <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>


  </head>

  <body>
    {% include 'includes/nav.html' %}
    <!-- Main content -->
    <div class="main-content" id="panel">
      <!-- Topnav -->
      {% include 'includes/top_nav.html' %}
      <!-- Header -->
      <!-- Header -->
      <div class="header bg-primary pb-6">
        <div class="container-fluid">
          <div class="header-body">
            <div class="row align-items-center py-4">
              <div class="col-lg-6 col-7">
                <h6 class="h2 text-white d-inline-block mb-0">{% block sub_breadscumb_highlight %}{% endblock %}</h6>
                <nav
                  aria-label="breadcrumb"
                  class="d-none d-md-inline-block ml-md-4"
                >
                  <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                    <li class="breadcrumb-item">
                      <a href="#">
                        {% block main_breadscumb %}{% endblock %}
                      </a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                      {% block sub_breadscumb %}{% endblock %}
                    </li>
                  </ol>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Page content -->
      <div class="container-fluid mt--6">
        {% block content %}
        {% endblock %}
      </div>
    </div>
    <!-- Argon JS -->
    <script src="{% static 'assets/js/dashboard.js' %}?v=1.2.0"></script>
    <!-- Demo JS - remove this in your project -->
    <script src="{% static 'assets/js/demo.min.js' %}"></script>
  </body>

</html>

templates/boards.html
{% extends "base.html" %}
{% load custom_tags %}
{% block content %}
    <h2>유저 리스트</h2>
    <h4>{%if msg%}{{msg}}{%endif%}</h4>
    <table class="table table-bordered">
      <thead>
        <th>ID</th>
        <th>유저이름</th>
        <th>이메일</th>
        <th>가입일</th>
        <th>페이플랜</th>
        <th>가격</th>
      </thead>
      {% for u in users %}
      <tr class={% cycle "table-dark" "" %}>
        <td>{{u.id}}</td>
        <td>{{u.username}}</td>
        <td>{{u.email|email_ma:u.id}}</td>
        <td>{{u.date_joined}}</td>
        <td>{{u.pay_plan.name}}</td>
        <td>{{u.pay_plan.price}}</td>
      </tr>
      {% endfor %}
    </table>


    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if users.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?p={{users.previous_page_number }}">이전으로</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="#">이전으로</a>
        </li>
        {% endif %}
        <li class="page-item">
          <a class="page-link" href="?p={{users.number|add:1 }}">{{users.number}}/{{users.paginator.num_pages}}</a>
        </li>
        {% if users.has_next %}
        <li class="page-item">
          <a class="page-link" href="?p={{users.next_page_number }}">다음으로</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="#">다음으로</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <p>
      <a href="{% url 'index' %}">홈으로</a>
      <a href="{% url 'register' %}">회원가입</a>
    </p>
    {% test_tags %}
    {% include "include_test.html" %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{welcome_msg}}
    <div>
        email: {{email}}
        
    </div>
    user : {{user}}

    <a href="{% url 'signup' %}">회원가입</a>
    <a href="{% url 'signout' %}">로그아웃</a>
</body>
</html>

templates/signin.html
{% load static %}
<!--
=========================================================
* Impact Design System - v1.0.0
=========================================================
* Product Page: https://www.creative-tim.com/product/impact-design-system
* Copyright 2010 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/impact-design-system/blob/master/LICENSE.md)
* Coded by Creative Tim
=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>Impact Dashboard - Login</title>

  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{% static 'assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'assets/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
  <!-- Page plugins -->
  <link rel="stylesheet" href="{% static 'assets/vendor/fullcalendar/dist/fullcalendar.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendor/sweetalert2/dist/sweetalert2.min.css' %}">
  <!-- Argon CSS -->
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" type="text/css">

</head>


<body class="bg-white">
  <!-- Main content -->
  <div class="main-content">
    <!-- Header -->
    <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
      <div class="container">
        <div class="header-body text-center mb-7">
          <div class="row justify-content-center">
            <div class="col-xl-5 col-lg-6 col-md-8 px-5">
              <h1 class="text-white">로그인</h1>
              <p class="text-lead text-white">Shrinkers에 오신것을 환영합니다.</p>
            </div>
          </div>
        </div>
      </div>
      <div class="separator separator-bottom separator-skew zindex-100">
        <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
        </svg>
      </div>
    </div>
    <!-- Page content -->
    <div class="container mt--9 pb-5 text-gray">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary border border-soft mb-0">
            <div class="card-header bg-transparent pb-5">
              <div class="text-center mt-2 mb-3"><small>소셜로 로그인 하기</small></div>
              <div class="btn-wrapper text-center">
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="{% static 'assets/img/icons/common/github.svg' %}"></span>
                  <span class="btn-inner--text">Github</span>
                </a>
                <a href="#" class="btn btn-neutral btn-icon">
                  <span class="btn-inner--icon"><img src="{% static 'assets/img/icons/common/google.svg' %}"></span>
                  <span class="btn-inner--text">Google</span>
                </a>
              </div>
            </div>
            <div class="card-body px-lg-5 py-lg-5">
              <div class="text-center mb-4">
                <small>이메일 로그인</small>
              </div>
              {% if msg %}
              <p class="text-center text-sm text-danger">{{ msg }}</p>
              {% endif %}
              {% if is_ok or user.is_authenticated %}
              <p class="text-center text-sm text-success">로그인 성공({{ user.username }}) <a class="text-primary" href="{% url 'auth:signout' %}">로그아웃</a></p>
              {% endif %}
              <form method="post">
                {% csrf_token %}
                <div class="form-group mb-3">
                  <div class="input-group input-group-merge input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-user-run"></i></span>
                    </div>
                    {{ form.email }}
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative">
                    <div class="input-group-prepend">
                      <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                    </div>
                    {{ form.password }}
                  </div>
                </div>
                <div class="custom-control custom-control-alternative custom-checkbox">
                  {{ form.remember_me }}
                  <label class="custom-control-label" for="_loginRememberMe">
                    <span>로그인 유지하기</span>
                  </label>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-primary my-4">로그인</button>
                </div>
              </form>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="#" class="text-gray"><small>비밀번호 찾기</small></a>
            </div>
            <div class="col-6 text-right">
              <a href="#" class="text-gray"><small>회원가입</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="{% static 'assets/vendor/jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/js-cookie/js.cookie.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
  <!-- Argon JS -->
  <script src="{% static 'assets/js/dashboard.js' %}?v=1.2.0"></script>
  <!-- Demo JS - remove this in your project -->
  <script src="{% static 'assets/js/demo.min.js' %}"></script>
</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>FastCampus Django</title>
  </head>
  <body>
    <h2>회원가입</h2>
    <h4>{%if msg%}{{msg}}{%endif%}</h4>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">가입하기</button>
    </form>
    <a href="{% url 'index' %}">홈으로</a>
  </body>
</html>

templates/url_create.html
{% extends 'base.html' %}
{% load static %}
{% block title%}단축 URL 생성{% endblock %}
{% block sub_breadscumb %}URL 생성{% endblock %}
{% block main_breadscumb%}URL 리스트{% endblock %}
{% block sub_breadscumb_highlight %}단축 URL {% endblock%}
{% block content %}

<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header border-0">
        <div class="row align-items-center">
            {% if is_update %}
            <h3>{{form.nick_name.value}} 수정하기</h5>
            {% else %}
            <h3>단축 URL 만들기</h5>
            {% endif %}
        </div>
      </div>
      <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                {% for f in form.visible_fields %}
                <div class="col-6">
                    <label>{{ f.label }}</label>
                    {{ f }}
                </div>
                {% endfor %}
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-success mt-5">
                    {% if is_update %}
                        {{form.nick_name.value}} 수정
                    {% else %}
                        생성
                    {% endif %}
                </button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/url_list.html
{% extends 'base.html' %}
{% load static %}
{% block title%}URL 리스트{% endblock %}
{% block main_breadscumb%}대시보드{% endblock %}
{% block sub_breadscumb_highlight %}URL List{% endblock%}
{% block sub_breadscumb %}URL 리스트{% endblock %}
{% block content %}

<div class="row">
  <div class="col-xl-12">
    <div class="card">
      <div class="card-header border-0">
        <a href="{% url 'urls:url_create' %}" class="btn btn-primary btn-sm font-size-12 float-right">
          추가
        </a>
      </div>
      <div class="table-responsive">
        <!-- Projects table -->
        <table class="table align-items-center table-flush">
          <thead class="thead-light">
            <tr>
              <th scope="col">별칭</th>
              <th scope="col">이동 URL</th>
              <th scope="col">단축 URL</th>
              <th scope="col">생성채널</th>
              <th scope="col">생성일</th>
              <th scope="col">액션</th>
            </tr>
          </thead>
          <tbody>
          {% for l in list%}
            <tr>
              <th scope="row">{{ l.nick_name }}</th>
              <td>{{ l.target_url }}</td>
              <td><a href="/{{ l.prefix }}/{{ l.shortened_url }}" target="_blank">
                  {{ request.get_host }}/{{ l.prefix }}/{{ l.shortened_url }}
                </a></td>
              <td>{{ l.created_via }}</td>
              <td>{{ l.created_at }}</td>
              <td>
                <form action="/urls/delete/{{ l.id }}" method="POST">
                {% csrf_token %}
                  <a href="/urls/update/{{ l.id }}" class="btn btn-sm btn-primary">
                    수정
                  </a>
                  <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('정말 삭제 하시겠습니까?');">
                    삭제
                  </button>
                </form>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

    <div id="vue_div">
    <span> Hello Times: [[ howManyTimes ]] </span>
        <a href="" class="btn-sm btn-primary text-white" @click="howManyTimes += 1">Say Hello</a>
    </div>

{% if messages %}
    {% for message in messages %}
    <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
      <div class="toast" style="position: absolute; top: 0; right: 0;"  data-delay="5000">
        <div class="toast-header">
          <strong class="mr-auto">알림</strong>
          <small>방금 전</small>
          <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="toast-body">
          {{message}}
        </div>
      </div>
    </div>
    {% endfor %}
    <script>
      $('.toast').toast('show');
    </script>
{% endif %}
    <script>
    let vue = new Vue({
        delimiters : ["[[", "]]"],
        el: "#vue_div",
        data: {
            howManyTimes: 0
        }
    })
</script>
{% endblock %}